### ISSUE TITLE
Line and Column Spacing

### ISSUE THREAD

**Issue by ipxfer** [any-block/obsidian-any-block#79] opened 2024-10-17 15:56 UTC
Hi - 

First, nice plug-in.

- In reading view, all the lines seem to be double spaced.   Any way to change that to single space?  Live view is showing single spacing.

- It appears that first column of [list2mdtimeline] or [list2c2t] are a bit too wide.  Is there way to control the width?

Thanks.

![image](https://github.com/user-attachments/assets/e5dd1356-300a-41aa-9e5d-3f308594c356)

**Comment by LincZero** [comment] 2024-10-17 22:47
## first column width

In the next version, I'll add 'ab-custom-td1-0' classes by default to timeline (even if the first column is as small as possible.

You can fix it temporarily, like this:

![图片](https://github.com/user-attachments/assets/99378b2c-92c4-451b-928d-30362cb001a3)

## double spaced

I remember the old version had this problem. Are you using the latest version of anyblock? 

![图片](https://github.com/user-attachments/assets/8a93eb36-465b-4df6-8fc8-68b5ebc8326d)

If the problem persists after the update, or you should provide a source md that can be replicated.

**Comment by ipxfer** [comment] 2024-10-18 22:45
Hi - 

First column workaround is working great.

As for the double space, here are the screenshots:

**Source**
![image](https://github.com/user-attachments/assets/ccf42797-0915-4ae8-90aa-416588cfcf8a)

**Live View**
![image](https://github.com/user-attachments/assets/486acc43-0d72-4543-b2bd-279b3ce7b3e6)

**Reading View**
Addition to the double spaced line, compared to Live View, first column is top vertically aligned while second is center vertically aligned as well.
![image](https://github.com/user-attachments/assets/7daa1bc3-bd72-4f9b-bb62-396728cb9a28)

**AnyBlock version**
![image](https://github.com/user-attachments/assets/193cc4c5-21db-44ff-89ff-03fac3e9b59c)

Thanks.

**Comment by LincZero** [comment] 2024-10-18 23:49
I know, this problem is caused by the cell content auto-wrap policy, I fixed the problem before the time to fix, so I do not repeat.

The two issues have been addressed in the newly released version 3.1.7

**Closed** 2024-10-19 00:08 UTC
Labels: bug
